### ISSUE TITLE
As an Admin I want to have a control panel to manage news, entries, and categories

### ISSUE THREAD

**Issue by kerstin97** [Araz0/gisHamer#5]

**Comment by Araz0** [comment]
created a simple interface to display the options:
![image](https://user-images.githubusercontent.com/19777742/177675983-0a59835b-3fe4-4254-b62b-e7876b732f6a.png)

icons used from https://lordicon.com/pricing (free Personal & commercial use )

**Comment by Araz0** [comment]
added simple styling for better UX... polishing is needed in the end.
closing issue since no more functionality is neeed.
