### ISSUE TITLE
As a user I can click on an entry and read more about the entry

### ISSUE THREAD

**Issue by kerstin97** [Araz0/gisHamer#9]
- [x] Add support for dialog pop-ups when clicking on an entry
- [x] Style dialog pop-up.
- [x] Fill in all the needed data for each entry and category (including links, tooltip, color, ... etc..).

**Comment by Araz0** [comment]
are we still implementing this issue? or did we decide on dropping it?

**Comment by Araz0** [comment]
styling is good but not perfect. polishing of the styling will be done at the end
